# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='imag',
            new_name='img',
        ),
    ]
