# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='mem_id',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
