# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20160811_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mem_id',
            field=models.IntegerField(),
        ),
    ]
