# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20160819_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebr_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='new')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
